#!/usr/bin/env bash
#
# This code builds the RODOS rom and reports the available byte space left after compilation.
#
do_error() {
    # Report if ROM exceeds &4000 bytes
    #
    grep "zz_END_OF_ROM_CODE" $tmpfile |awk -F "$" '{print "0x"$2}'|awk -n -F "$" '{print "Exceeded rom size by "$1" bytes\n"}'
    echo "Error: ROM exceeded 0x4000 bytes"; rm $tmpfile; exit 255
    }

show_space() {
    # Show the available space in the ROM
    #
    grep "zz_END_OF_ROM_CODE" $tmpfile |awk -F "$" '{print "0x"$2}'|awk -n -F "$" '{if ($1 == 0x0000) print "No More Space in ROM"; else print 0xffff-$1" bytes remaining in rom"}'
}

# Make sure we have something to assemble.
if [ -z "$1" ]; then
    echo "Please supply a z80 assembly file"
    exit 255
else
    #Generate a temp file for label reporting
    tmpfile=`mktemp -p .`
    #tmpfile="labels.txt"
    echo "Compiling with: $1 $2 $3 $4 $5"
    z80asm -L $1 $2 $3 $4 $5 2>$tmpfile
    if [ $? -gt 0 ]; then
        grep -vi equ  $tmpfile
        echo "z80asm error $?"
	    #rm $tmpfile
        exit 1
    fi

    #|| err=$?;grep -v equ $tmpfile; exit $err
    #Note: If zz_END_OF_ROM_CODE is $0000 then we are perfectly sized. If thats the case we'll make romend=0x10000 just to make bash happy.
    romend=`grep "zz_END_OF_ROM_CODE" $tmpfile |awk -F "$" '{if ($2=="0000") print "0x1"$2; else print "0x"$2}'`

    #echo "a"$msg
    [[ $romend -lt 0xc000 ]] && do_error || show_space;echo "Compiled successfully"
    rm $tmpfile
fi
